### ISSUE TITLE
Syntax error running on Ubuntu 14.04

### ISSUE THREAD

**Issue by nicolargo** [desbma/hddfancontrol#2]
On an Ubuntu 14.04 desktop:

    $ sudo pip install hddfancontrol
    => Install OK

Then:

```
$ sudo hddfancontrol 
Traceback (most recent call last):
  File "/usr/local/bin/hddfancontrol", line 9, in <module>
    load_entry_point('hddfancontrol==1.1.2', 'console_scripts', 'hddfancontrol')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 474, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2260, in load
    ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/hddfancontrol/__init__.py", line 449
    print(desc, end=" ", flush=True)
                   ^
SyntaxError: invalid syntax
```

**Comment by desbma** [comment]
You are using Python 2.7, and to quote the readme:
> HDD Fan control needs Python >= 3.3.

On Ubuntu 14.04, install with `pip3` instead of `pip`:
`sudo pip3 install hddfancontrol`
and it should work.
